// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fzaigpqfziswokotwyac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6YWlncHFmemlzd29rb3R3eWFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI2MjY3MjksImV4cCI6MjA4ODIwMjcyOX0.9NWGFKF-FhGlNUf7UnScqx5ZtLmgGmb565COLQL6_Ss";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});