// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://elavsxhviwdhwvtzehpi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsYXZzeGh2aXdkaHd2dHplaHBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzODMwNTAsImV4cCI6MjA3Mzk1OTA1MH0.5OwJe4r41CR7ZD1_xEUjI6k1N448georAKgi1tZJGYw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});